pipeline:
  vendor:
    image: composer
    commands:
    - composer install
    when:
      local: false

  style:
    group: tests
    image: 104corp/php-testing:7.1
    commands:
    - php vendor/bin/phpcs

  unit:
    group: tests
    image: 104corp/php-testing:7.1
    commands:
    - php vendor/bin/phpunit
