sudo: false
os: linux
dist: trusty
language: php

php:
- 7.0
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly

branches:
 only:
  - master

install:
- composer install --prefer-dist

cache:
  directories:
  # See https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
  - $HOME/.composer/cache/files
  - vendor

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then bash <(curl -s https://codecov.io/bash) ; fi

notifications:
  email:
   recipients:
      - x4d1q5t4w1g0e1g5@104corp.slack.com
   on_success: awlays # default: change
   on_failure: always # default: always